"""Pydantic data models for the Cowork agent engine."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


# --- Enums ---


class TaskStatus(str, Enum):
    PLANNING = "planning"
    RUNNING = "running"
    CONFIRMING = "confirming"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class PermissionTier(str, Enum):
    AUTO = "auto"
    NOTIFY = "notify"
    CONFIRM = "confirm"
    BLOCKED = "blocked"


# --- Task & Step Models ---


class Task(BaseModel):
    id: str
    goal: str
    status: TaskStatus = TaskStatus.PLANNING
    attached_files: list[str] = Field(default_factory=list)
    result_summary: str | None = None
    deliverable_dir: str | None = None
    total_steps: int = 0
    completed_steps: int = 0
    tokens_used: int = 0
    error_message: str | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None


class Step(BaseModel):
    id: str
    task_id: str
    step_number: int
    tool_name: str
    tool_args: dict = Field(default_factory=dict)
    description: str
    status: StepStatus = StepStatus.PENDING
    result: dict | None = None
    error: str | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None


class Deliverable(BaseModel):
    id: str
    task_id: str
    file_path: str
    file_type: str
    file_size: int | None = None
    description: str | None = None


# --- Agent Models ---


class PlanStep(BaseModel):
    """A single planned step from the LLM planner."""

    step_number: int
    tool: str
    args: dict = Field(default_factory=dict)
    reason: str


class Plan(BaseModel):
    """Full plan generated by the LLM."""

    steps: list[PlanStep]
    reasoning: str


class ToolResult(BaseModel):
    """Result returned by tool execution."""

    success: bool
    data: dict | None = None
    error: str | None = None
    needs_confirmation: bool = False
    confirmation_message: str | None = None


class ConfirmationRequest(BaseModel):
    """Sent to UI when a destructive operation needs user approval."""

    action_id: str
    task_id: str
    operation: str
    description: str
    file_path: str
    destination: str | None = None


# --- Config Models ---


class LLMConfig(BaseModel):
    provider: str = "openai"
    model: str = "gpt-4o"
    api_key: str | None = None
    base_url: str | None = None
    endpoint: str | None = None
    deployment: str | None = None
    api_version: str | None = "2024-12-01-preview"
    max_tokens: int = 4096
    temperature: float = 0.3


class PermissionConfig(BaseModel):
    allowed_paths: list[str] = Field(default_factory=list)
    confirm_destructive: bool = True
    dry_run: bool = False


class AgentConfig(BaseModel):
    max_steps_per_task: int = 50
    max_replans: int = 3
    task_timeout_seconds: int = 600


class AppConfig(BaseModel):
    llm: LLMConfig = Field(default_factory=LLMConfig)
    permissions: PermissionConfig = Field(default_factory=PermissionConfig)
    agent: AgentConfig = Field(default_factory=AgentConfig)


# --- JSON-RPC Models ---


class RPCRequest(BaseModel):
    jsonrpc: str = "2.0"
    method: str
    params: dict = Field(default_factory=dict)
    id: int | str | None = None


class RPCResponse(BaseModel):
    jsonrpc: str = "2.0"
    result: dict | None = None
    error: dict | None = None
    id: int | str | None = None


class RPCEvent(BaseModel):
    """Event pushed from sidecar to host (notification, no id)."""

    jsonrpc: str = "2.0"
    method: str
    params: dict = Field(default_factory=dict)
