"""Tests for file system tools."""

import pytest

from cowork.agent.context import TaskContext
from cowork.tools.fs import (
    CreateDirectoryTool,
    GetFileInfoTool,
    ListDirectoryTool,
    ReadFileTool,
    WriteFileTool,
)


def _make_context() -> TaskContext:
    return TaskContext(task_id="test-001", goal="test")


@pytest.mark.asyncio
async def test_list_directory(tmp_path):
    # Create some test files
    (tmp_path / "file1.txt").write_text("hello")
    (tmp_path / "file2.md").write_text("world")
    (tmp_path / "subdir").mkdir()

    tool = ListDirectoryTool()
    result = await tool.execute({"path": str(tmp_path)}, _make_context())

    assert result.success
    assert result.data["total_files"] == 2
    assert result.data["total_dirs"] == 1
    names = [e["name"] for e in result.data["entries"]]
    assert "file1.txt" in names
    assert "subdir" in names


@pytest.mark.asyncio
async def test_list_directory_not_found():
    tool = ListDirectoryTool()
    result = await tool.execute({"path": "/nonexistent/path"}, _make_context())
    assert not result.success
    assert "Not a directory" in result.error


@pytest.mark.asyncio
async def test_read_file(tmp_path):
    content = "Hello, Cowork!\nLine 2\nLine 3"
    (tmp_path / "test.txt").write_text(content)

    tool = ReadFileTool()
    result = await tool.execute({"path": str(tmp_path / "test.txt")}, _make_context())

    assert result.success
    assert result.data["content"] == content
    assert result.data["lines"] == 3
    assert not result.data["truncated"]


@pytest.mark.asyncio
async def test_read_file_not_found():
    tool = ReadFileTool()
    result = await tool.execute({"path": "/nonexistent/file.txt"}, _make_context())
    assert not result.success


@pytest.mark.asyncio
async def test_write_file_new(tmp_path):
    path = str(tmp_path / "output.md")
    tool = WriteFileTool()

    # For new files, write_file shouldn't need confirmation
    tool.requires_confirmation = False

    result = await tool.execute(
        {"path": path, "content": "# Output\nGenerated by Cowork."},
        _make_context(),
    )

    assert result.success
    assert result.data["created"]
    assert not result.data["overwritten"]
    assert (tmp_path / "output.md").read_text() == "# Output\nGenerated by Cowork."


@pytest.mark.asyncio
async def test_get_file_info(tmp_path):
    (tmp_path / "test.pdf").write_bytes(b"fake pdf content")

    tool = GetFileInfoTool()
    result = await tool.execute({"path": str(tmp_path / "test.pdf")}, _make_context())

    assert result.success
    assert result.data["name"] == "test.pdf"
    assert result.data["extension"] == "pdf"
    assert result.data["type"] == "file"


@pytest.mark.asyncio
async def test_create_directory(tmp_path):
    new_dir = tmp_path / "a" / "b" / "c"

    tool = CreateDirectoryTool()
    result = await tool.execute({"path": str(new_dir)}, _make_context())

    assert result.success
    assert new_dir.exists()
